# Generated by Django 4.2.2 on 2023-10-23 18:22

import dealership.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('brand', models.CharField(default='', max_length=120)),
                ('guarantee', models.CharField(default='', max_length=120)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('cylinder_capacity', models.IntegerField()),
                ('power', models.IntegerField()),
                ('maximum_capacity', models.IntegerField()),
                ('doors', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gearbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateOfUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.brand')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=dealership.models.CarImage.get_upload_path)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.carmodel'),
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.category'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.fuel'),
        ),
        migrations.AddField(
            model_name='car',
            name='gearbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.gearbox'),
        ),
        migrations.AddField(
            model_name='car',
            name='state_of_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.stateofuse'),
        ),
    ]
