# Generated by Django 4.2.6 on 2023-10-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='car',
            name='cylinder_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='car',
            name='gearbox',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='car',
            name='guarantee',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='car',
            name='maximum_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='state_of_use',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
